enum EnumStore {
	TABLE = 'TABLE',
	MENU = 'MENU',
	POPUP = 'POPUP',
	ORDER = 'ORDER',

	EMPLOYEES = 'EMPLOYEES',
	MENU_ELEMETS = 'MENU_ELEMETS',
	TABLES = 'TABLES',
	DISHES = 'DISHES',
	RESTAURANTS = 'RESTAURANTS',
}

export default EnumStore;
